#!/usr/bin/env python3
"""Materialize the audited official TT100K release as a 221-class YOLO dataset.

TT100K is retained in its original fine-grained taxonomy for external
pretraining. It is intentionally not collapsed to the three CCTSDB classes:
the detector will later be fine-tuned on CCTSDB, which replaces the class head.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import tempfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from PIL import Image


DEFAULT_OUTPUT = Path("data/processed/tt100k_221")
SOURCE_TO_TARGET_SPLIT = {"train": "train", "other": "val", "test": "test"}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def resolve_data_root(raw: Path) -> Path:
    raw = raw.resolve()
    candidates = [raw, raw / "data"]
    matches = [candidate for candidate in candidates if (candidate / "annotations.json").is_file()]
    if len(matches) != 1:
        raise FileNotFoundError(f"Expected exactly one TT100K data root with annotations.json below {raw}; found {matches}")
    return matches[0]


def read_ids(path: Path) -> list[str]:
    if not path.is_file():
        raise FileNotFoundError(f"Missing official split IDs: {path}")
    ids = [line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if len(ids) != len(set(ids)):
        raise ValueError(f"Duplicate image ID in {path}")
    return ids


def link_or_copy(source: Path, target: Path) -> str:
    try:
        os.link(source, target)
        return "hardlink"
    except OSError:
        shutil.copy2(source, target)
        return "copy"


def remove_default_output(path: Path) -> None:
    if path.resolve() != DEFAULT_OUTPUT.resolve():
        raise RuntimeError(f"--force only permits replacing the default output: {DEFAULT_OUTPUT}")
    shutil.rmtree(path)


def write_data_yaml(path: Path, dataset_root: Path, categories: list[str]) -> None:
    lines = [
        "# Generated by scripts/prepare_tt100k.py; preserve all 221 TT100K categories for pretraining.",
        f"path: {json.dumps(str(dataset_root.resolve()))}",
        "train: images/train",
        "val: images/val",
        "test: images/test",
        "names:",
    ]
    lines.extend(f"  {index}: {json.dumps(category)}" for index, category in enumerate(categories))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Prepare audited TT100K as a 221-class YOLO pretraining dataset")
    parser.add_argument("--raw", type=Path, required=True, help="TT100K release directory or its parent directory")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--force", action="store_true", help="Replace only the default output directory")
    args = parser.parse_args()

    raw = args.raw.resolve()
    output = args.output.resolve()
    data_root = resolve_data_root(raw)
    if output.exists():
        if not args.force:
            raise FileExistsError(f"Output exists: {output}; rerun with --force only for {DEFAULT_OUTPUT}")
        remove_default_output(output)
    if output == raw or raw in output.parents:
        raise ValueError("Output must not be inside the raw TT100K release")

    annotation_path = data_root / "annotations.json"
    annotation = json.loads(annotation_path.read_text(encoding="utf-8"))
    if set(annotation) != {"imgs", "types"} or not isinstance(annotation["types"], list):
        raise ValueError("Unexpected TT100K annotations.json structure")
    categories = [str(category) for category in annotation["types"]]
    if len(categories) != len(set(categories)):
        raise ValueError("Duplicate category code in TT100K annotations")
    if not isinstance(annotation["imgs"], dict):
        raise ValueError("This official TT100K release must store imgs as a dictionary keyed by image ID")
    records_by_path: dict[str, dict[str, object]] = {}
    for image_id, record in annotation["imgs"].items():
        if not isinstance(record, dict) or not isinstance(record.get("path"), str):
            raise ValueError(f"Invalid image record for ID {image_id!r}")
        relative = record["path"]
        if relative in records_by_path:
            raise ValueError(f"Duplicate annotation image path: {relative}")
        records_by_path[relative] = record
    class_to_index = {category: index for index, category in enumerate(categories)}
    split_ids = {split: read_ids(data_root / split / "ids.txt") for split in SOURCE_TO_TARGET_SPLIT}
    expected_paths = {f"{split}/{image_id}.jpg" for split, image_ids in split_ids.items() for image_id in image_ids}
    extras = set(records_by_path) - expected_paths
    if extras:
        raise ValueError(f"Annotation paths outside official split ID files: {len(extras)}")

    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix="tt100k_build_", dir=output.parent))
    materialization: Counter[str] = Counter()
    split_images: Counter[str] = Counter()
    split_instances: Counter[str] = Counter()
    split_backgrounds: Counter[str] = Counter()
    category_instances: Counter[str] = Counter()
    clipped_boxes = 0
    try:
        for target_split in SOURCE_TO_TARGET_SPLIT.values():
            (temporary / "images" / target_split).mkdir(parents=True)
            (temporary / "labels" / target_split).mkdir(parents=True)
        for source_split, target_split in SOURCE_TO_TARGET_SPLIT.items():
            for image_id in split_ids[source_split]:
                relative = f"{source_split}/{image_id}.jpg"
                source_image = data_root / relative
                if not source_image.is_file():
                    raise FileNotFoundError(f"Missing official TT100K image: {source_image}")
                image_target = temporary / "images" / target_split / f"{image_id}.jpg"
                materialization[link_or_copy(source_image, image_target)] += 1
                split_images[target_split] += 1
                record = records_by_path.get(relative)
                label_lines: list[str] = []
                if record is None:
                    split_backgrounds[target_split] += 1
                else:
                    with Image.open(source_image) as image:
                        width, height = image.size
                    objects = record.get("objects", [])
                    if not isinstance(objects, list):
                        raise ValueError(f"Invalid object list for {relative}")
                    for obj in objects:
                        if not isinstance(obj, dict):
                            raise ValueError(f"Invalid object in {relative}")
                        category = str(obj.get("category", ""))
                        if category not in class_to_index:
                            raise ValueError(f"Unknown TT100K category {category!r} in {relative}")
                        bbox = obj.get("bbox")
                        if not isinstance(bbox, dict):
                            raise ValueError(f"Missing bbox for {category!r} in {relative}")
                        try:
                            xmin, ymin = float(bbox["xmin"]), float(bbox["ymin"])
                            xmax, ymax = float(bbox["xmax"]), float(bbox["ymax"])
                        except (KeyError, TypeError, ValueError) as exc:
                            raise ValueError(f"Malformed bbox for {category!r} in {relative}") from exc
                        bounded = (max(0.0, min(xmin, width)), max(0.0, min(ymin, height)), max(0.0, min(xmax, width)), max(0.0, min(ymax, height)))
                        if bounded != (xmin, ymin, xmax, ymax):
                            clipped_boxes += 1
                        xmin, ymin, xmax, ymax = bounded
                        box_width, box_height = xmax - xmin, ymax - ymin
                        if box_width <= 0 or box_height <= 0:
                            raise ValueError(f"Non-positive bbox after bounds check for {category!r} in {relative}")
                        x_center, y_center = (xmin + xmax) / 2 / width, (ymin + ymax) / 2 / height
                        label_lines.append(f"{class_to_index[category]} {x_center:.6f} {y_center:.6f} {box_width / width:.6f} {box_height / height:.6f}")
                        split_instances[target_split] += 1
                        category_instances[category] += 1
                (temporary / "labels" / target_split / f"{image_id}.txt").write_text("\n".join(label_lines) + ("\n" if label_lines else ""), encoding="utf-8")

        manifests = temporary / "manifests"
        manifests.mkdir()
        # Write the final output path into YAML even though files are built in
        # a temporary sibling directory before the atomic rename below.
        write_data_yaml(temporary / "tt100k_221.yaml", output, categories)
        manifest = {
            "schema_version": 1,
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "source": {
                "raw_root": str(raw),
                "data_root": str(data_root),
                "annotation_file": str(annotation_path),
                "annotation_sha256": sha256(annotation_path),
                "taxonomy": "Official TT100K 221 fine-grained classes retained without semantic remapping",
            },
            "source_to_target_split": SOURCE_TO_TARGET_SPLIT,
            "target": {"root": str(output), "yaml": "tt100k_221.yaml", "classes": {str(index): category for index, category in enumerate(categories)}},
            "splits": {
                split: {"images": split_images[split], "instances": split_instances[split], "background_images": split_backgrounds[split]}
                for split in ("train", "val", "test")
            },
            "instances_by_category": {category: category_instances[category] for category in categories},
            "materialization": dict(materialization),
            "clipped_boxes": clipped_boxes,
            "raw_data_modified": False,
            "next_step": "Use this dataset only for 221-class TT100K pretraining. Fine-tune a new 3-class head on the locked CCTSDB train/dev split before any CCTSDB official-test evaluation.",
        }
        (manifests / "dataset_manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        os.replace(temporary, output)
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise
    print(json.dumps({"prepared": str(output), "splits": manifest["splits"], "classes": len(categories), "materialization": dict(materialization), "clipped_boxes": clipped_boxes}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
