#!/usr/bin/env python3
"""Optimized YOLO train presets for this server:

  CPU: i7-8700K 6C/12T | RAM 32GB | GPU RTX 3090 24GB | $HOME often NFS

Bottleneck fix order:
  1) Stage data off NFS → local (/tmp/...)
  2) workers=4–6 + optional cache=ram
  3) larger batch (96–128) once GPU is fed

Usage:
  # Best path
  python scripts/stage_data_local.py --dst /tmp/cctsdb2021_full
  python scripts/train_3090.py --local-data /tmp/cctsdb2021_full --model yolo11n.pt

  # Still on NFS (slower but safer than workers=0 forever)
  python scripts/train_3090.py --preset nfs --model yolo11n.pt

  # YOLOv8 after 11n finishes (sequential recommended)
  python scripts/train_3090.py --local-data /tmp/cctsdb2021_full --model yolov8n.pt --name yolov8n_cctsdb_full
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def write_local_yaml(data_root: Path) -> Path:
    out = Path("configs/cctsdb2021_full_local.yaml")
    out.write_text(
        f"""# auto-generated by train_3090.py
path: {data_root.resolve().as_posix()}
train: train/images
val: test/images
test: test/images
names:
  0: prohibitory
  1: mandatory
  2: warning
nc: 3
""",
        encoding="utf-8",
    )
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="3090-optimized YOLO train")
    parser.add_argument("--model", default="yolo11n.pt")
    parser.add_argument(
        "--preset",
        choices=["nfs", "local", "auto"],
        default="auto",
        help="nfs: safe on network FS | local: fast SSD | auto: local if --local-data else nfs",
    )
    parser.add_argument(
        "--local-data",
        type=Path,
        default=None,
        help="Path to staged YOLO root (train/images, test/images)",
    )
    parser.add_argument("--data", type=Path, default=None, help="Override data yaml")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--batch", type=int, default=None)
    parser.add_argument("--workers", type=int, default=None)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--device", default="0")
    parser.add_argument("--name", default=None)
    parser.add_argument("--project", default="runs/detect")
    parser.add_argument("--patience", type=int, default=50)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument(
        "--cache",
        default=None,
        help="false|ram|disk — default depends on preset",
    )
    args = parser.parse_args()

    # Prefer conda libstdc++ (OpenCV ABI issues on this server)
    conda = os.environ.get("CONDA_PREFIX")
    if conda:
        os.environ["LD_LIBRARY_PATH"] = f"{conda}/lib:" + os.environ.get(
            "LD_LIBRARY_PATH", ""
        )

    preset = args.preset
    if preset == "auto":
        preset = "local" if args.local_data else "nfs"

    if args.local_data:
        root = args.local_data
        if not (root / "train" / "images").exists():
            print(f"ERROR: {root}/train/images missing — run stage_data_local.py first")
            return 1
        data_yaml = args.data or write_local_yaml(root)
    else:
        data_yaml = args.data or Path("configs/cctsdb2021_full.yaml")

    if not Path(data_yaml).exists():
        print(f"ERROR: data yaml not found: {data_yaml}")
        return 1

    # Presets tuned for i7-8700K + 32GB + 3090
    if preset == "nfs":
        workers = 2 if args.workers is None else args.workers
        batch = 64 if args.batch is None else args.batch
        cache: bool | str = False
        # keep cache build single-threaded on NFS
        try:
            import ultralytics.utils as u

            u.NUM_THREADS = 2
        except Exception:
            pass
    else:  # local
        workers = 6 if args.workers is None else args.workers
        batch = 96 if args.batch is None else args.batch
        cache = "ram"

    if args.cache is not None:
        c = args.cache.lower()
        cache = False if c in {"false", "0", "none", "off"} else c

    name = args.name or f"{Path(str(args.model)).stem}_cctsdb_full_{preset}"

    print("=== train_3090 preset ===")
    print(f"  preset   : {preset}")
    print(f"  data     : {data_yaml}")
    print(f"  model    : {args.model}")
    print(f"  batch    : {batch} | workers={workers} | cache={cache}")
    print(f"  epochs   : {args.epochs} | name={name}")
    if preset == "nfs":
        print("  NOTE: still on NFS-ish path — stage to /tmp for big speedup")
        print("    python scripts/stage_data_local.py --dst /tmp/cctsdb2021_full")

    try:
        from ultralytics import YOLO
    except ImportError as e:
        print("ERROR: ultralytics import failed:", e)
        print("  export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH")
        return 1

    model = YOLO(args.model)
    model.train(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=batch,
        device=args.device,
        workers=workers,
        cache=cache,
        plots=False,
        exist_ok=True,
        project=args.project,
        name=name,
        pretrained=True,
        resume=args.resume,
        patience=args.patience,
        # reduce startup disk thrash
        save_period=-1,
    )
    print("Done. Weights under runs/detect/", name, "/weights/best.pt")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
